### ISSUE TITLE
Chrome crashes.

### ISSUE THREAD

**Issue by SinghVerm** [chithakumar13/FIFA-ClickAutoBuyer#10]
app stucks at please wait trying to login. as chrome immediately crashes when i click on start account.

**Comment by rafig-javadov** [comment]
> app stucks at please wait trying to login. as chrome immediately crashes when i click on start account.

donwload chromedriver v8 and replace the file in the AutoBuyer Folder

**Comment by chithakumar13** [comment]
Check #8
