### ISSUE TITLE
License Expires

### ISSUE THREAD

**Issue by SinghVerm** [chithakumar13/FIFA-ClickAutoBuyer#11]
how i can renew it?

**Comment by chithakumar13** [comment]
Full access is currently available for only paterons as people were asking for paterons only features.

In few days , i will make it versions for everyone , in the meanwhile you can try the other autobuyer.

**Comment by SinghVerm** [comment]
please let me know the patreon link. I would like to join that. Cant find it anywhere. Want to support the work you are doing

**Comment by chithakumar13** [comment]
https://www.patreon.com/i_m_ck13

**Comment by SinghVerm** [comment]
whats the difference between $2, or $5 subscription? any more features in 5?

**Comment by chithakumar13** [comment]
For now , its the same for all subscription. Might add few tier based benefits in future..
