### ISSUE TITLE
Chrome Window closes when launching

### ISSUE THREAD

**Issue by diogoperas** [chithakumar13/FIFA-ClickAutoBuyer#8]
Hi! 

From today (yesterday was working fine) when clicking "Start Account" the bot opens the Chrome window but then it closes automatically in a fraction of a second.

**Comment by chithakumar13** [comment]
i think you have updated your browser

just download the chromedriver from here chromedriver.storage.googleapis.com/index.html?path=88.0.4324.96

and replace it with the one in the autobuyer folder
